/*
 * File: app/view/UserWindow.js
 *
 * This file was generated by Sencha Architect version 2.2.2.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('RestfulAdmin.view.UserWindow', {
    extend: 'Ext.window.Window',

    autoShow: true,
    height: 250,
    itemId: 'userWindow',
    width: 400,
    layout: {
        type: 'fit'
    },
    title: 'Kullanıcı',
    modal: true,

    initComponent: function() {
        var me = this;

        Ext.applyIf(me, {
            items: [
                {
                    xtype: 'form',
                    layout: {
                        align: 'stretch',
                        type: 'vbox'
                    },
                    bodyPadding: 10,
                    items: [
                     
                        {
                            xtype: 'textfield',
                            fieldLabel: 'isim',
                            name: 'firstName',
                            tabIndex: 1,
                            allowBlank: false
                        },
                        {
                            xtype: 'textfield',
                            fieldLabel: 'Soyisim',
                            name: 'lastName',
                            tabIndex: 2,
                            allowBlank: false
                        },
						{
                            xtype: 'textfield',
                            fieldLabel: 'sifre',
                            name: 'password',
                            inputType: 'password',
                            tabIndex: 3,
                            allowBlank: false
                        },
						{
                            xtype: 'textfield',
                            fieldLabel: 'Kullanıcı_No',
                            name: 'username',
                            tabIndex: 4,
                            allowBlank: false
                        },
                        {
                            xtype: 'checkboxfield',
                            fieldLabel: ' ',
                            labelSeparator: '',
                            name: 'enabled',
                            tabIndex: 5,
                            boxLabel: 'Yetki'
                        },
                        {
                            xtype: 'button',
                            handler: function(button, event) {
                                var form = button.up('form');
                                var record = form.getRecord();
                                var store = Ext.getStore('Users');

                                if (form.isValid()) {
                                    if (Ext.isEmpty(record)) {
                                        store.add(form.getValues());
                                    } else {
                                        form.updateRecord();    
                                    }
                                    Ext.getStore('Users').sync();
                                    button.up('window').close();
                                }
                            },
                            flex: 1,
                            tabIndex: 6,
                            text: 'Kaydet'
                        },
                        {
                            xtype: 'button',
                            handler: function(button, event) {
                                button.up('window').close();
                            },
                            flex: 1,
                            text: 'Vazgec'
                        }
                    ]
                }
            ]
        });

        me.callParent(arguments);
    }

});